version: '3.8'

services:
  nginx:
    image: nginx:1.21
    container_name: nginx
    ports:
      - "4001:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/html:/var/www/html
    depends_on:
      - php
    networks:
      - frontend
      - backend

  php:
    image: php:7.4-fpm
    container_name: php
    volumes:     
      - ./nginx/html:/var/www/html
    networks:
      - backend

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.1
    container_name: phpmyadmin
    ports:
      - "6001:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: example
    depends_on:
      - mysql
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  mysql-data:
